### ISSUE TITLE
Warning message: There is no coordinates for languages...

### ISSUE THREAD

**Issue by IndianaTones** [cran/lingtypology#1]
Apologies if this is not a LingTypology issue per se, but just noting that when I use Glottolog as the source for coordinates, sometimes I get the above warning message even though the coordinates for the language(s) in question are indeed to be found in Glottolog.

Advice is greatly appreciated :)

**Comment by gaborcsardi** [comment]
Thanks! This is a read only mirror of CRAN, please see the real package authors in the `DESCRIPTION` file. Thanks again!

**Comment by IndianaTones** [comment]
oh gosh wrong place sorry!!!
